Fixes #400
usnistgov/metaschema pull request #401
Opened 2023-07-21 12:15 UTC by RS-Credentive

# Committer Notes

Addresses
 #400 

### All Submissions:

- [ ] Have you followed the guidelines in our [Contributing](https://github.com/usnistgov/metaschema/blob/master/CONTRIBUTING.md) document?
- [ ] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/usnistgov/metaschema/pulls) for the same update/change?
- [ ] Have you squashed any non-relevant commits and commit messages? \[[instructions](https://git-scm.com/book/en/v2/Git-Tools-Rewriting-History)\]
- [ ] Do all automated CI/CD checks pass?

### Changes to Core Features:

- [ ] Have you added an explanation of what your changes do and why you'd like us to include them?
- [ ] Have you written new tests for your core changes, as applicable?
- [ ] Have you included examples of how to use your new feature(s)?
- [ ] Have you updated all website](https://pages.nist.gov/metaschema) and readme documentation affected by the changes you made? Changes to the website can be made in the website/content directory of your branch.

2023-07-21 12:17 UTC, RS-Credentive commented
I have not updated the documentation on the website, as I believe it is automatically generated from the schema itself.

2023-07-24 17:38 UTC, aj-stein-nist approved these changes
I am but a bit player here, but I like it!

2023-07-24 17:43 UTC, david-waltermire-nist requested changes
@RS-Credentive Thanks for the submission. The XML changes look good.

Can you make the same changes to the [JSON data types](https://github.com/usnistgov/metaschema/blob/develop/schema/json/metaschema-datatypes.json)? These need to be kept in sync.

2023-07-24 17:46 UTC, RS-Credentive commented
> 

No problem. Thanks for the heads up. I thought they were autogenerated from the metaschema, or I would have already done so.

2023-07-24 17:48 UTC, david-waltermire-nist commented on schema/xml/metaschema-datatypes.xsd
> +			<xs:pattern value="(((2000|2400|2800|(19|2[0-9](0[48]|[2468][048]|[13579][26])))-02-29)|(((19|2[0-9])[0-9]{2})-02-(0[1-9]|1[0-9]|2[0-8]))|(((19|2[0-9])[0-9]{2})-(0[13578]|10|12)-(0[1-9]|[12][0-9]|
Thinking about this more, we should use the same patterns as are used in dateTime.

```suggestion
			<xs:pattern value="(((2000|2400|2800|(19|2[0-9](0[48]|[2468][048]|[13579][26])))-02-29)|(((19|2[0-9])[0-9]{2})-02-(0[1-9]|1[0-9]|2[0-8]))|(((19|2[0-9])[0-9]{2})-(0[13578]|10|12)-(0[1-9]|[12][0-9]|3[01]))|(((19|2[0-9])[0-9]{2})-(0[469]|11)-(0[1-9]|[12][0-9]|30)))(Z|(-((0[0-9]|1[0-2]):00|0[39]:30)|\+((0[0-9]|1[0-4]):00|(0[34569]|10):30|(0[58]|12):45)))?"/>
```

2023-07-24 17:48 UTC, david-waltermire-nist commented on schema/xml/metaschema-datatypes.xsd
> +			<xs:pattern value="(((2000|2400|2800|(19|2[0-9](0[48]|[2468][048]|[13579][26])))-02-29)|(((19|2[0-9])[0-9]{2})-02-(0[1-9]|1[0-9]|2[0-8]))|(((19|2[0-9])[0-9]{2})-(0[13578]|10|12)-(0[1-9]|[12][0-9]|
```suggestion
			<xs:pattern value="(((2000|2400|2800|(19|2[0-9](0[48]|[2468][048]|[13579][26])))-02-29)|(((19|2[0-9])[0-9]{2})-02-(0[1-9]|1[0-9]|2[0-8]))|(((19|2[0-9])[0-9]{2})-(0[13578]|10|12)-(0[1-9]|[12][0-9]|3[01]))|(((19|2[0-9])[0-9]{2})-(0[469]|11)-(0[1-9]|[12][0-9]|30)))(Z|(-((0[0-9]|1[0-2]):00|0[39]:30)|\+((0[0-9]|1[0-4]):00|(0[34569]|10):30|(0[58]|12):45)))"/>
```

2023-07-24 18:06 UTC, RS-Credentive commented
Updated JSON to reflect the new timezones regex you recommended.

2023-07-26 14:39 UTC, david-waltermire-nist approved these changes
Looks good. Thank you for the additional edits.

2023-07-29 14:30 UTC, david-waltermire-nist approved these changes

2023-07-29 14:32 UTC, merged