Document `has-cardinality` constraint
usnistgov/metaschema pull request #547
Opened 2024-02-21 19:53 UTC by aj-stein-nist

# Committer Notes

Closes #546.

### All Submissions:

- [ ] Have you followed the guidelines in our [Contributing](https://github.com/usnistgov/metaschema/blob/master/CONTRIBUTING.md) document?
- [ ] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/usnistgov/metaschema/pulls) for the same update/change?
- [ ] Have you squashed any non-relevant commits and commit messages? \[[instructions](https://git-scm.com/book/en/v2/Git-Tools-Rewriting-History)\]
- [ ] Do all automated CI/CD checks pass?

### Changes to Core Features:

- [ ] Have you added an explanation of what your changes do and why you'd like us to include them?
- [ ] Have you written new tests for your core changes, as applicable?
- [ ] Have you included examples of how to use your new feature(s)?
- [ ] Have you updated all website](https://pages.nist.gov/metaschema) and readme documentation affected by the changes you made? Changes to the website can be made in the website/content directory of your branch.

2024-02-21 22:19 UTC, david-waltermire commented on website/content/specification/syntax/constraints.md
> +
Need a statement that defines how the constraint is determined to pass or fail.

2024-02-21 22:19 UTC, david-waltermire requested changes
Please clarify how to determine if the constraint passes or fails.

2024-02-22 02:52 UTC, aj-stein-nist commented
Woops, did some bad `git` foo. Restored locally and PR reopened. 😆

2024-02-23 13:17 UTC, david-waltermire approved these changes

2024-02-23 13:17 UTC, merged